mindmap
  root((project))
    domains
      subdomains
        nested subdomains
      EmailAddress
      apps
    PersonOfInterest
      emails
      repos
      companies
      social accounts
      phone numbers
      org memberships
      Credentials
    GitHubOrg
      Repositories
      commits
      members
    GitHubRepo
      Committers
      branches
      forks
      Credentials
    Service
      Credential
        username
        token
        key
        secret
